#index:
#    path: /
#    controller: App\Controller\DefaultController::index
register:
    path: /register
    controller: App\Controller\ApiController::register
    methods: POST
api_login_check:
    path: /api/login_check
  


